name: frontend-test-and-deploy

on:
  push:
    branches: ["master"]
    paths:
      - "resources/config/frontend.edn"
      - "resources/public/**"
      - "src/frontend/**"
      - "src/common/**"
      - "test/frontend/**"
      - "Dockerfile.frontend"
      - "project.clj"
      - "shadow-cljs.clj"
      - "karma.conf.js"
      - "tailwind.config.js"
      - "package.json"
      - "package-lock.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run frontend tests
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hs-challenge-frontend:latest
          build-args: |
            BACKEND_URL=${{ secrets.BACKEND_URL }}
